# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_util.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_util.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ftest_util.proto\"\x0f\n\rTestUtilEmpty28\n\x0cTestUtilPing\x12(\n\x04Ping\x12\x0e.TestUtilEmpty\x1a\x0e.TestUtilEmpty\"\x00\x62\x06proto3')
)




_TESTUTILEMPTY = _descriptor.Descriptor(
  name='TestUtilEmpty',
  full_name='TestUtilEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=34,
)

DESCRIPTOR.message_types_by_name['TestUtilEmpty'] = _TESTUTILEMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestUtilEmpty = _reflection.GeneratedProtocolMessageType('TestUtilEmpty', (_message.Message,), {
  'DESCRIPTOR' : _TESTUTILEMPTY,
  '__module__' : 'test_util_pb2'
  # @@protoc_insertion_point(class_scope:TestUtilEmpty)
  })
_sym_db.RegisterMessage(TestUtilEmpty)



_TESTUTILPING = _descriptor.ServiceDescriptor(
  name='TestUtilPing',
  full_name='TestUtilPing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=36,
  serialized_end=92,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='TestUtilPing.Ping',
    index=0,
    containing_service=None,
    input_type=_TESTUTILEMPTY,
    output_type=_TESTUTILEMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTUTILPING)

DESCRIPTOR.services_by_name['TestUtilPing'] = _TESTUTILPING

# @@protoc_insertion_point(module_scope)
